### ISSUE TITLE
Failure discovering EP25

### ISSUE THREAD

**Issue by ryanquinn3** [ZeliardM/homebridge-kasa-python#10]
**Describe The Bug:**

I have a few EP25 smart outlets and when they are on the network, this plug is failing to boot up.

I'd be happy to put together a patch for this if you can point me in the right direction!

**To Reproduce:**

1. Have an EP25 setup and on the local network. 
2. Add this plugin to homebridge

**Expected behavior:**

Device discovery would work and the plugin would boot up successfully.

**Logs:**

```
[12/2/2024, 8:49:37 PM] [KasaPython] Discovery request sent successfully
[12/2/2024, 8:49:37 PM] [KasaPython] Devices discovered: 4
[12/2/2024, 8:49:37 PM] [KasaPython] Reading config file from path: /var/lib/homebridge/config.json
[12/2/2024, 8:49:37 PM] [KasaPython] Config file read successfully
[12/2/2024, 8:49:37 PM] [KasaPython] KasaPython configuration found in config file
[12/2/2024, 8:49:37 PM] [KasaPython] Filtering manualDevices to remove entries without a host
[12/2/2024, 8:49:37 PM] [KasaPython] Processing discovered devices
[12/2/2024, 8:49:37 PM] [KasaPython] Processed device with IP: 192.168.0.143
[12/2/2024, 8:49:37 PM] [KasaPython] Processed device with IP: 192.168.0.151
[12/2/2024, 8:49:37 PM] [KasaPython] Processed device with IP: 192.168.0.160
[12/2/2024, 8:49:37 PM] [KasaPython] Processed device with IP: 192.168.0.242
[12/2/2024, 8:49:37 PM] [KasaPython] Writing updated config file
[12/2/2024, 8:49:37 PM] [KasaPython] Config file written successfully
[12/2/2024, 8:49:37 PM] [KasaPython] Platform config updated
[12/2/2024, 8:49:37 PM] [KasaPython] Adding: [null] SMART.KASAPLUG [803A01166017656BF9F4687C991F06EE23011E7D]
[12/2/2024, 8:49:37 PM] [KasaPython] [null] Creating new Accessory [803A01166017656BF9F4687C991F06EE23011E7D] [a163ca93-4392-4a1f-b33b-44b915e7fe0c] category: OUTLET
[12/2/2024, 8:49:37 PM] [KasaPython] An error occurred during startup: AssertionError [ERR_ASSERTION]: Accessories must be created with a non-empty displayName.
    at new Accessory (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:495:11)
    at new PlatformAccessory (/var/lib/homebridge/node_modules/homebridge/src/platformAccessory.ts:72:9)
    at HomeKitDevicePlug.initializeAccessory (file:///var/lib/homebridge/node_modules/homebridge-kasa-python/src/devices/index.ts:47:19)
    at new HomekitDevice (file:///var/lib/homebridge/node_modules/homebridge-kasa-python/src/devices/index.ts:36:37)
    at new HomeKitDevicePlug (file:///var/lib/homebridge/node_modules/homebridge-kasa-python/src/devices/homekitPlug.ts:18:5)
    at create (file:///var/lib/homebridge/node_modules/homebridge-kasa-python/src/devices/create.ts:34:12)
    at KasaPythonPlatform.createHomekitDevice (file:///var/lib/homebridge/node_modules/homebridge-kasa-python/src/platform.ts:168:12)
    at KasaPythonPlatform.foundDevice (file:///var/lib/homebridge/node_modules/homebridge-kasa-python/src/platform.ts:375:48)
    at file:///var/lib/homebridge/node_modules/homebridge-kasa-python/src/platform.ts:226:16
    at Array.forEach (<anonymous>) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: null,
  expected: true,
  operator: '=='
}
```

**Plugin Config:**

```json
{
  "name":"KasaPython",
  "enableCredentials":true,
  "username": "*****",
  "password":"****",
  "manualDevices":[],
  "platform":"KasaPython"
}
```

**Environment:**

* **Plugin Version**: 2.6.8
* **Homebridge Version**: 1.8.5
* **Node.js Version**: 20.18.1
* **NPM Version**: 10.8.2
* **Operating System**:  Raspbian

**Comment by ZeliardM** [comment]
What version of the plugin are you using? You didn't list that.

It seems that it's failing with the alias of the plug in question. Do you have the plugs named in the Kasa/Tapo app anything in particular?

**Comment by ZeliardM** [comment]
Would you be able to run the following commands from the Homebridge Web UI Terminal:
cd kasa-python
source .venv/bin/activate
kasa --json --username 'username' --password 'password' discover

You must have the username and password in single quotes.

Let me know if you can do that for me and get the output posted here. Please make sure to scrub any personal information from the output. I will need any alias or nickname output for the outlets in question.

Thanks.

**Comment by ryanquinn3** [comment]
> What version of the plugin are you using? You didn't list that.

Sorry about that. Its the latest version 2.6.8. Updated my initial post to reflect that.

> Would you be able to run the following commands from the Homebridge Web UI Terminal:

Heres the response from the kasa py cli for one of those smart outlets. I've included just one of them to not add too much noise to the debugging process.

```
{
   
    "192.168.0.210": {
        "component_nego": {
            "component_list": [
                {
                    "id": "device",
                    "ver_code": 2
                },
                {
                    "id": "firmware",
                    "ver_code": 2
                },
                {
                    "id": "quick_setup",
                    "ver_code": 3
                },
                {
                    "id": "time",
                    "ver_code": 1
                },
                {
                    "id": "wireless",
                    "ver_code": 1
                },
                {
                    "id": "schedule",
                    "ver_code": 2
                },
                {
                    "id": "countdown",
                    "ver_code": 2
                },
                {
                    "id": "antitheft",
                    "ver_code": 1
                },
                {
                    "id": "account",
                    "ver_code": 1
                },
                {
                    "id": "synchronize",
                    "ver_code": 1
                },
                {
                    "id": "sunrise_sunset",
                    "ver_code": 1
                },
                {
                    "id": "led",
                    "ver_code": 1
                },
                {
                    "id": "cloud_connect",
                    "ver_code": 1
                },
                {
                    "id": "iot_cloud",
                    "ver_code": 1
                },
                {
                    "id": "device_local_time",
                    "ver_code": 1
                },
                {
                    "id": "default_states",
                    "ver_code": 1
                },
                {
                    "id": "auto_off",
                    "ver_code": 2
                },
                {
                    "id": "energy_monitoring",
                    "ver_code": 2
                },
                {
                    "id": "power_protection",
                    "ver_code": 1
                },
                {
                    "id": "homekit",
                    "ver_code": 2
                },
                {
                    "id": "current_protection",
                    "ver_code": 1
                }
            ]
        },
        "get_device_info": {
            "device_id": "803AA6BC1B462A7A0C4731CC96B53FC923036DE9",
            "fw_ver": "1.0.3 Build 240529 Rel.145252",
            "hw_ver": "2.6",
            "type": "SMART.KASAPLUG",
            "model": "EP25",
            "mac": "A8-6E-84-FD-AF-C2",
            "hw_id": "651A215C54B3520474193575A358E0CC",
            "fw_id": "00000000000000000000000000000000",
            "oem_id": "1646D188F56641C3AE3B08FFB032AEF9",
            "ip": "192.168.0.210",
            "time_diff": 0,
            "ssid": "ZGVld2h5",
            "rssi": -49,
            "signal_level": 3,
            "auto_off_status": "off",
            "auto_off_remain_time": 0,
            "longitude": -1879048193,
            "latitude": -1879048193,
            "lang": "",
            "avatar": "",
            "region": "",
            "specs": "",
            "nickname": "",
            "has_set_location_info": false,
            "device_on": true,
            "on_time": 6187,
            "default_states": {
                "type": "last_states",
                "state": {}
            },
            "overheat_status": "normal",
            "power_protection_status": "normal",
            "overcurrent_status": "normal"
        },
        "get_connect_cloud_state": {
            "status": 0
        },
        "get_auto_off_config": {
            "enable": false,
            "delay_min": 120
        },
        "get_energy_usage": {
            "today_runtime": 136,
            "month_runtime": 535,
            "today_energy": 480,
            "month_energy": 1915,
            "local_time": "2024-12-03 13:59:29",
            "electricity_charge": [
                0,
                0,
                0
            ],
            "current_power": 220078
        },
        "get_current_power": {
            "current_power": 220
        },
        "get_auto_update_info": {
            "enable": true,
            "time": 180,
            "random_range": 120
        },
        "get_led_info": {
            "night_mode": {
                "night_mode_type": "sunrise_sunset",
                "start_time": 1140,
                "end_time": 420,
                "sunrise_offset": 0,
                "sunset_offset": 0
            },
            "led_status": true,
            "led_rule": "always",
            "bri_config": {
                "bri_type": "overall",
                "overall_bri": 50
            }
        },
        "get_device_time": {
            "time_diff": 0,
            "timestamp": 1733234369,
            "region": ""
        }
    }
```

**Comment by ZeliardM** [comment]
Yea, the nickname field is empty. I guess you did not name the plug when you added it in the Kasa/Tapo App? I will create a default alias to be used if the alias is empty and push out an update in a bit. Thanks!

**Comment by ryanquinn3** [comment]
> I guess you did not name the plug when you added it in the Kasa/Tapo App

Ah this makes sense. Those plugs have native homekit capabilities so I didn't even download the kasa app. I set those EP25s up before opening up another kasa power strip that doesn't have homekit support. The powerstrips lack of homekit led me to setup homebridge and this library last night. 

> I will create a default alias to be used if the alias is empty and push out an update in a bit.

Thank you very much for your help and for crafting this library!

**Comment by ZeliardM** [comment]
Ok, so since the plugs are already in HomeKit, you wouldn't want to add them twice I suppose. Maybe I can look at adding a way to filter out devices with native HomeKit support as well.

**Comment by ryanquinn3** [comment]
> Ok, so since the plugs are already in HomeKit, you wouldn't want to add them twice I suppose

Yeah since the nickname issue prevents them from being pulled into homebridge, it's been working just fine already. I unplugged them all and then left my power strip in and got the power strip discovered correctly, then re-plugged in the oulets. I assumed I would just be able to manually exclude them if they were properly discovered. If that isn't possible today, that would be awesome to add in. I'm still quite new to homebridge so this was my first attempt at getting things connected.

**Comment by ZeliardM** [comment]
That'll work for now, but if the plugin or Homebridge restarts, it'll lock up again. Let me keep working on how to filter out HomeKit native devices and I'll let you know.

**Comment by ZeliardM** [comment]
@ryanquinn3 Ok, leave everything plugged in and update to v2.6.11 and let me know if it only adds the HS300 power strip.

**Comment by ZeliardM** [comment]
@ryanquinn3 try v2.6.13 and let me know. Thanks!

**Comment by ryanquinn3** [comment]
@ZeliardM Just got around to upgrading. It worked perfectly. Thank you so much! I'll go ahead and close this issue.
