### ISSUE TITLE
Errors with v2.7.0-beta.2

### ISSUE THREAD

**Issue by MichaelCWarren** [ZeliardM/homebridge-kasa-python#13]
I'm getting this when running with the latest beta 2.7.0-beta.2.

```
Traceback (most recent call last):

  File "<string>", line 32, in __mashumaro_from_dict__
  File "<string>", line 19, in __mashumaro_from_dict__

ValueError: Argument for kasa.credentials.Credentials.__mashumaro_from_dict__ method should be a dict instance


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/homebridge/node_modules/homebridge-kasa-python/dist/python/kasaApi.py", line 370, in <module>
    uvicorn.run(app, host="0.0.0.0", port=port, loop="asyncio")
    │       │   │                         └ 34573
    │       │   └ <Quart 'kasaApi'>
    │       └ <function run at 0x7f80c3d6cae0>
    └ <module 'uvicorn' from '/var/lib/homebridge/kasa-python/.venv/lib/python3.12/site-packages/uvicorn/__init__.py'>

  File "/var/lib/homebridge/kasa-python/.venv/lib/python3.12/site-packages/uvicorn/main.py", line 579, in run
    server.run()
    │      └ <function Server.run at 0x7f80c3d6f740>
    └ <uvicorn.server.Server object at 0x7f80c39213d0>
  File "/var/lib/homebridge/kasa-python/.venv/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7f80c3d6f7e0>
           │       │   └ <uvicorn.server.Server object at 0x7f80c39213d0>
           │       └ <function run at 0x7f80c4ab8680>
           └ <module 'asyncio' from '/usr/lib/python3.12/asyncio/__init__.py'>
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           │      │   └ <coroutine object Server.serve at 0x7f80c1fab760>
           │      └ <function Runner.run at 0x7f80c3ec3100>
           └ <asyncio.runners.Runner object at 0x7f80c250c530>
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-6' coro=<Server.serve() running at /var/lib/homebridge/kasa-python/.venv/lib/python3.12/site-package...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x7f80c3ec0d60>
           │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x7f80c250c530>
  File "/usr/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7f80c3ec0cc0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7f80c3ec2ac0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1987, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f80c4014fe0>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x7f80c05b68f0>()>
  File "/usr/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <_asyncio.TaskStepMethWrapper object at 0x7f80c05b68f0>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <_asyncio.TaskStepMethWrapper object at 0x7f80c05b68f0>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x7f80c05b68f0>()>
  File "/var/lib/homebridge/kasa-python/.venv/lib/python3.12/site-packages/quart/asgi.py", line 98, in handle_request
    response = await self.app.handle_request(request)
                     │    │   │              └ <Request 'http://127.0.0.1:34573/getSysInfo' [POST]>
                     │    │   └ <function Quart.handle_request at 0x7f80c1fe85e0>
                     │    └ <Quart 'kasaApi'>
                     └ <quart.asgi.ASGIHTTPConnection object at 0x7f80c05b5df0>
  File "/var/lib/homebridge/kasa-python/.venv/lib/python3.12/site-packages/quart/app.py", line 1404, in handle_request
    return await self.full_dispatch_request(request_context)
                 │    │                     └ <quart.ctx.RequestContext object at 0x7f80c05b7800>
                 │    └ <function Quart.full_dispatch_request at 0x7f80c1fe8720>
                 └ <Quart 'kasaApi'>
  File "/var/lib/homebridge/kasa-python/.venv/lib/python3.12/site-packages/quart/app.py", line 1440, in full_dispatch_request
    result = await self.dispatch_request(request_context)
                   │    │                └ <quart.ctx.RequestContext object at 0x7f80c05b7800>
                   │    └ <function Quart.dispatch_request at 0x7f80c1fe8a40>
                   └ <Quart 'kasaApi'>
  File "/var/lib/homebridge/kasa-python/.venv/lib/python3.12/site-packages/quart/app.py", line 1536, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore
                 │    │            │          │        └ {}
                 │    │            │          └ <Request 'http://127.0.0.1:34573/getSysInfo' [POST]>
                 │    │            └ <function get_sys_info_route at 0x7f80c1feaca0>
                 │    └ <function Quart.ensure_async at 0x7f80c1fdbce0>
                 └ <Quart 'kasaApi'>

> File "/homebridge/node_modules/homebridge-kasa-python/dist/python/kasaApi.py", line 336, in get_sys_info_route
    sys_info = await get_sys_info(device_config)
                     │            └ {'connection_type': {'device_family': 'IOT.SMARTPLUGSWITCH', 'encryption_type': 'XOR', 'https': False}, 'credentials': Creden...
                     └ <function get_sys_info at 0x7f80c1fea840>

  File "/homebridge/node_modules/homebridge-kasa-python/dist/python/kasaApi.py", line 242, in get_sys_info
    dev = await Device.connect(config=Device.Config.from_dict(device_config))
                │      │              │      │      │         └ {'connection_type': {'device_family': 'IOT.SMARTPLUGSWITCH', 'encryption_type': 'XOR', 'https': False}, 'credentials': Creden...
                │      │              │      │      └ <classmethod(<function __mashumaro_from_dict__ at 0x7f80c34a5b20>)>
                │      │              │      └ <class 'kasa.deviceconfig.DeviceConfig'>
                │      │              └ <class 'kasa.device.Device'>
                │      └ <staticmethod(<function Device.connect at 0x7f80c2a0b9c0>)>
                └ <class 'kasa.device.Device'>

  File "<string>", line 34, in __mashumaro_from_dict__

mashumaro.exceptions.InvalidFieldValue: Field "credentials" of type Optional[Credentials] in DeviceConfig has invalid value Credentials()
[12/6/2024, 7:07:19 PM] [KasaPython] 2024-12-06 19:07:19.264 | ERROR    | __main__:get_sys_info_route:339 - Error getting system info: Field "credentials" of type Optional[Credentials] in DeviceConfig has invalid value Credentials()
```

Also, I discovered (before you updated), that it is seeing my dimmer switches as a bulb and trying to get the color_temp resulting in the following error (I think from the kasa-python) library.

`
[12/6/2024, 6:02:14 PM] [KasaPython] 2024-12-06 18:02:14.380 | DEBUG    | __main__:custom_sysinfo_config_serializer:44 - Serializing device: 192.168.4.62
[12/6/2024, 6:02:14 PM] [KasaPython] 2024-12-06 18:02:14.382 | ERROR    | __main__:create_device_info:212 - Error creating device info for 192.168.4.62: Bulb does not support colortemp.
`

**Comment by ZeliardM** [comment]
@MichaelCWarren The second error was from me, not properly catching what was what for the device info, it should be fixed in beta.2.

As for the first issue, it has something to do with how I'm passing the credentials, going to try something and let you know.

**Comment by ZeliardM** [comment]
@MichaelCWarren give v2.7.0-beta.3 a try and let me know.

**Comment by MichaelCWarren** [comment]
Looks like we're close.  These are some problems I see now.

```
[12/7/2024, 4:27:53 PM] [KasaPython] Unknown device type: {
  sys_info: {
    alias: 'Lights',
    child_num: 0,
    device_id: '8006963671511E280A75368D9E8A48DE2211110B',
    device_type: 'IOT.SMARTPLUGSWITCH',
    host: '192.168.4.52',
    hw_ver: '1.0',
    mac: 'A8:42:A1:75:DF:63',
    state: true,
    sw_ver: '1.0.8 Build 240424 Rel.101842'
  },
  disc_info: { model: 'KS200(US)' },
  feature_info: {},
  device_config: {
    connection_type: {
      device_family: 'IOT.SMARTPLUGSWITCH',
      encryption_type: 'XOR',
      https: false
    },
    credentials: {
      password: pw,
      username: un
    },
    host: '192.168.4.52',
    timeout: 5,
    uses_http: false
  }
}
[12/7/2024, 4:27:53 PM] [KasaPython] Adding: [Plug #3] SMART.TAPOPLUG [8022CBFEEB4730D98CC38A3AE9A2CC9D2331247C]
[12/7/2024, 4:27:53 PM] [KasaPython] Unknown device type: {
  sys_info: {
    alias: 'Plug #3',
    child_num: 0,
    device_id: '8022CBFEEB4730D98CC38A3AE9A2CC9D2331247C',
    device_type: 'SMART.TAPOPLUG',
    host: '192.168.4.53',
    hw_ver: '1.0',
    mac: 'B0:19:21:99:59:3E',
    state: true,
    sw_ver: '1.1.3 Build 240523 Rel.175054'
  },
  disc_info: { model: 'P115(US)' },
  feature_info: {},
  device_config: {
    connection_type: {
      device_family: 'SMART.TAPOPLUG',
      encryption_type: 'KLAP',
      https: false
    },
    credentials: {
      password: pw,
      username: un
    },
    host: '192.168.4.53',
    timeout: 5,
    uses_http: true
  }
}
[12/7/2024, 4:27:53 PM] [KasaPython] Adding: [Plug #4] SMART.TAPOPLUG [80221648450C447544AD147427EE20D423310C17]
[12/7/2024, 4:27:53 PM] [KasaPython] Unknown device type: {
  sys_info: {
    alias: 'Plug #4',
    child_num: 0,
    device_id: '80221648450C447544AD147427EE20D423310C17',
    device_type: 'SMART.TAPOPLUG',
    host: '192.168.4.54',
    hw_ver: '1.0',
    mac: 'B0:19:21:99:61:54',
    state: true,
    sw_ver: '1.1.3 Build 240523 Rel.175054'
  },
  disc_info: { model: 'P115(US)' },
  feature_info: {},
  device_config: {
    connection_type: {
      device_family: 'SMART.TAPOPLUG',
      encryption_type: 'KLAP',
      https: false
    },
    credentials: {
      password: pw,
      username: un
    },
    host: '192.168.4.54',
    timeout: 5,
    uses_http: true
  }
}
[12/7/2024, 4:27:53 PM] [KasaPython] Adding: [Plug #5] SMART.TAPOPLUG [802203F0BE4F0819F4B63D76F35DE7C623304406]
[12/7/2024, 4:27:53 PM] [KasaPython] Unknown device type: {
  sys_info: {
    alias: 'Plug #5',
    child_num: 0,
    device_id: '802203F0BE4F0819F4B63D76F35DE7C623304406',
    device_type: 'SMART.TAPOPLUG',
    host: '192.168.4.55',
    hw_ver: '1.0',
    mac: 'B0:19:21:99:54:BE',
    state: true,
    sw_ver: '1.1.3 Build 240523 Rel.175054'
  },
  disc_info: { model: 'P115(US)' },
  feature_info: {},
  device_config: {
    connection_type: {
      device_family: 'SMART.TAPOPLUG',
      encryption_type: 'KLAP',
      https: false
    },
     credentials: {
      password: pw,
      username: un
    },
    host: '192.168.4.55',
    timeout: 5,
    uses_http: true
  }
}
[12/7/2024, 4:27:53 PM] [KasaPython] Adding: [Plug #6] SMART.TAPOPLUG [80220063F8FC08B605533DD7BBE7F6FA233147E5]
[12/7/2024, 4:27:53 PM] [KasaPython] Unknown device type: {
  sys_info: {
    alias: 'Plug #6',
    child_num: 0,
    device_id: '80220063F8FC08B605533DD7BBE7F6FA233147E5',
    device_type: 'SMART.TAPOPLUG',
    host: '192.168.4.56',
    hw_ver: '1.0',
    mac: 'B0:19:21:99:62:00',
    state: true,
    sw_ver: '1.1.3 Build 240523 Rel.175054'
  },
  disc_info: { model: 'P115(US)' },
  feature_info: {},
  device_config: {
    connection_type: {
      device_family: 'SMART.TAPOPLUG',
      encryption_type: 'KLAP',
      https: false
    },
    credentials: {
      password: pw,
      username: un
    },
    host: '192.168.4.56',
    timeout: 5,
    uses_http: true
  }
}
```

**Comment by ZeliardM** [comment]
@MichaelCWarren give v2.7.0-beta.4 a shot and let me know how it's working.

**Comment by MichaelCWarren** [comment]
@ZeliardM beta.4 seems to be running very well for me at the moment.  I'll keep an eye on it and let you know.  Thanks for all your help.  This is great!

**Comment by ZeliardM** [comment]
@MichaelCWarren Excellent, I've got some clean-up to do on the config side of things, going to add in some additional variables for items in discovery and also looking at adding the ability for a discovery automation cycle throughout the life of the plugin.

**Comment by MichaelCWarren** [comment]
If you do that, may I suggest maybe make the "auto cleanup" of cached accessories a little less aggressive?  Or make it optional?  I've noticed when playing with the betas (the earlier ones), if the discovery fails for any reason, it cleans up all the accessories.  This wipes out all of the HomeKit setup.

**Comment by ZeliardM** [comment]
@MichaelCWarren I can make it optional, it would be difficult to make it less aggressive since the only thing is to compare active accessories vs cached accessories and then unregister them. Have any ideas for that?

**Comment by ZeliardM** [comment]
@MichaelCWarren I decided I'll add an offline interval in the settings. The devices will handle flags for last_seen and offline and after the device has been offline past the interval, it will remove them. Sound good?

**Comment by MichaelCWarren** [comment]
That's makes a lot of sense to me.
