### ISSUE TITLE
Error in Python Check with Python

### ISSUE THREAD

**Issue by jakepez** [ZeliardM/homebridge-kasa-python#17]
**Describe The Bug:**
Running Homebridge Docker container. Testing updating to Ubuntu:latest - in order to support Python 3.12 (proposed changes to official Homebridge Docker - https://github.com/homebridge/docker-homebridge/pull/576/commits/6dcbaff4cc3092857b317fd68d51166e7799e1d1) 

**To Reproduce:**
Using container here: https://hub.docker.com/repository/docker/jakepez/homebridge/tags
Install KasaPython

**Expected behavior:**
KasaPython finds python3 / pip3 and starts up properly

**Logs:**
```log
[12/13/2024, 2:44:00 AM] Homebridge v2.0.0-beta.23 (HAP v1.1.1-beta.7) (KasaPython) is running on port 46383.
[12/13/2024, 2:44:00 AM] [KasaPython] homebridge-kasa-python v2.7.0-beta.6, node v22.12.0, homebridge v2.0.0-beta.23, api v2.7 Initializing...
[12/13/2024, 2:44:01 AM] [KasaPython] [Python Check] Traceback (most recent call last):
  File "/var/lib/homebridge/kasa-python/.venv/bin/pip3", line 5, in <module>
[12/13/2024, 2:44:01 AM] [KasaPython] [Python Check] from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'
[12/13/2024, 2:44:01 AM] [KasaPython] [Python Check] Traceback (most recent call last):
  File "/var/lib/homebridge/kasa-python/.venv/bin/pip3", line 5, in <module>
[12/13/2024, 2:44:01 AM] [KasaPython] [Python Check] from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'
[12/13/2024, 2:44:01 AM] [KasaPython] [Python Check] Traceback (most recent call last):
  File "/var/lib/homebridge/kasa-python/.venv/bin/pip3", line 5, in <module>
[12/13/2024, 2:44:01 AM] [KasaPython] [Python Check] from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'
[12/13/2024, 2:44:01 AM] [KasaPython] [Python Check] Traceback (most recent call last):
  File "/var/lib/homebridge/kasa-python/.venv/bin/pip3", line 5, in <module>
[12/13/2024, 2:44:01 AM] [KasaPython] [Python Check] from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'
[12/13/2024, 2:44:31 AM] [KasaPython] An error occurred during startup: Error: Server did not respond within 30 seconds
    at waitForServer (file:///homebridge/node_modules/homebridge-kasa-python/src/platform.ts:99:9)
    at KasaPythonPlatform.didFinishLaunching (file:///homebridge/node_modules/homebridge-kasa-python/src/platform.ts:187:7)
    at HomebridgeAPI.<anonymous> (file:///homebridge/node_modules/homebridge-kasa-python/src/platform.ts:130:7)
```

**Plugin Config:**

```json
{
            "name": "KasaPython",
            "enableCredentials": false,
            "username": "name@email.com",
            "password": "tyrgem-fonGu4-cebseh",
            "manualDevices": [
                {
                    "host": "10.XX.XX.XX",
                    "alias": "Power Strip 7BC8"
                },
                {
                    "host": "10.XX.XX.XX",
                    "alias": "Power Strip 357E"
                },
                {
                    "host": "10.XX.XX.XX",
                    "alias": "Power Strip F777"
                }
            ],
            "_bridge": {
                "username": "XX:XX:XX:XX:XX:XX"
            },
            "platform": "KasaPython"
        },
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: Homebridge v2.0.0-beta.23 (HAP v1.1.1-beta.7)
* **Node.js Version**: node v22.12.0
* **NPM Version**: 10.9.0
* **Python Version**: root@Qnap:/var/lib/homebridge $ python3 --version
Python 3.12.3
root@Qnap:/var/lib/homebridge $ pip3 --version
pip 24.0 from /usr/lib/python3/dist-packages/pip (python 3.12)
root@Qnap:/var/lib/homebridge $
* **Operating System**: Docker

**Comment by ZeliardM** [comment]
@jakepez Can you enable debug logging on Homebridge and restart the plug-in and repost the logs? Thanks!

**Comment by ZeliardM** [comment]
@jakepez I'm going to push v2.7.0-beta.7 with a lot better debug logging. Make sure to enable debug in the Homebridge settings, install the new version and post the logs here, thanks!

**Comment by jakepez** [comment]
@ZeliardM here you go. I updated to beta.7 of the plugin.

Here are the python locations (versions provided in my first post):
```
# root@Qnap:/var/lib/homebridge $ which python3
/usr/bin/python3
# root@Qnap:/var/lib/homebridge $ which pip3
/usr/bin/pip3
```

Debug Logs
```
[12/13/2024, 5:01:51 PM] [KasaPython] Initializing KasaPython platform...
[12/13/2024, 5:01:51 PM] [KasaPython] Initializing child bridge 0E:D8:79:18:92:34
[12/13/2024, 5:01:53 PM] [KasaPython] Child bridge starting (pid 434)...
[12/13/2024, 5:01:53 PM] [KasaPython] Child bridge started successfully (plugin v2.7.0-beta.7).
[12/13/2024, 5:01:54 PM] [KasaPython] homebridge-kasa-python v2.7.0-beta.7, node v22.12.0, homebridge v2.0.0-beta.23, api v2.7 Initializing...
[12/13/2024, 5:01:54 PM] [KasaPython] [Python Check] Traceback (most recent call last):
  File "/var/lib/homebridge/kasa-python/.venv/bin/pip3", line 5, in <module>
[12/13/2024, 5:01:54 PM] [KasaPython] [Python Check] from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'
[12/13/2024, 5:01:54 PM] [KasaPython] [Python Check] Traceback (most recent call last):
  File "/var/lib/homebridge/kasa-python/.venv/bin/pip3", line 5, in <module>
[12/13/2024, 5:01:54 PM] [KasaPython] [Python Check] from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'
[12/13/2024, 5:01:54 PM] [KasaPython] [Python Check] Traceback (most recent call last):
  File "/var/lib/homebridge/kasa-python/.venv/bin/pip3", line 5, in <module>
[12/13/2024, 5:01:54 PM] [KasaPython] [Python Check] from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'
[12/13/2024, 5:01:54 PM] [KasaPython] [Python Check] Traceback (most recent call last):
  File "/var/lib/homebridge/kasa-python/.venv/bin/pip3", line 5, in <module>
[12/13/2024, 5:01:54 PM] [KasaPython] [Python Check] from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'
[12/13/2024, 5:02:25 PM] [KasaPython] Server did not respond within 30 seconds
[12/13/2024, 5:02:25 PM] [KasaPython] An error occurred during startup: Error: Server did not respond within 30 seconds
    at waitForServer (file:///homebridge/node_modules/homebridge-kasa-python/src/platform.ts:109:9)
    at KasaPythonPlatform.didFinishLaunching (file:///homebridge/node_modules/homebridge-kasa-python/src/platform.ts:222:7)
    at HomebridgeAPI.<anonymous> (file:///homebridge/node_modules/homebridge-kasa-python/src/platform.ts:142:7)
[12/13/2024, 5:03:22 PM] [KasaPython] Initializing KasaPython platform...
[12/13/2024, 5:03:22 PM] [KasaPython] Initializing child bridge 0E:D8:79:18:92:34
[12/13/2024, 5:03:24 PM] [KasaPython] Child bridge starting (pid 787)...
[12/13/2024, 5:03:25 PM] [KasaPython] Child bridge started successfully (plugin v2.7.0-beta.7).
[12/13/2024, 5:03:25 PM] Loaded 3 cached accessories from cachedAccessories.0ED879189234.
[12/13/2024, 5:03:25 PM] Homebridge v2.0.0-beta.23 (HAP v1.1.1-beta.7) (Nest) is running on port 55965.
[12/13/2024, 5:03:25 PM] [KasaPython] [Package Config] Loading package configuration from: /homebridge/node_modules/homebridge-kasa-python/package.json
[12/13/2024, 5:03:25 PM] [KasaPython] Configuring Platform Accessory: [Power Strip 357E] UUID: 77a07e6c-108b-4954-852b-cca541647dfd
[12/13/2024, 5:03:25 PM] [KasaPython] Platform Accessory [Power Strip 357E] last seen 91609ms ago, offline interval is 604800000ms, offline status: false
[12/13/2024, 5:03:25 PM] [KasaPython] Platform Accessory [Power Strip 357E] is online, updating lastSeen time.
[12/13/2024, 5:03:25 PM] [KasaPython] Platform Accessory [Power Strip 357E] with UUID [77a07e6c-108b-4954-852b-cca541647dfd] is not in configuredAccessories, adding it.
[12/13/2024, 5:03:25 PM] [KasaPython] Configuring Platform Accessory: [Power Strip 7BC8] UUID: 88f0d1d0-b7c9-410c-8654-937b6d223e4c
[12/13/2024, 5:03:25 PM] [KasaPython] Platform Accessory [Power Strip 7BC8] last seen 91610ms ago, offline interval is 604800000ms, offline status: false
[12/13/2024, 5:03:25 PM] [KasaPython] Platform Accessory [Power Strip 7BC8] is online, updating lastSeen time.
[12/13/2024, 5:03:25 PM] [KasaPython] Platform Accessory [Power Strip 7BC8] with UUID [88f0d1d0-b7c9-410c-8654-937b6d223e4c] is not in configuredAccessories, adding it.
[12/13/2024, 5:03:25 PM] [KasaPython] Configuring Platform Accessory: [Power Strip F777] UUID: 088009fd-7404-4d88-be61-3d88099b4eaa
[12/13/2024, 5:03:25 PM] [KasaPython] Platform Accessory [Power Strip F777] last seen 91607ms ago, offline interval is 604800000ms, offline status: false
[12/13/2024, 5:03:25 PM] [KasaPython] Platform Accessory [Power Strip F777] is online, updating lastSeen time.
[12/13/2024, 5:03:25 PM] Loaded 1 cached accessories from cachedAccessories.0EE5D81876D7.
[12/13/2024, 5:03:25 PM] Loaded 2 cached accessories from cachedAccessories.0E4B8A2DE8EC.
[12/13/2024, 5:03:25 PM] [KasaPython] Platform Accessory [Power Strip F777] with UUID [088009fd-7404-4d88-be61-3d88099b4eaa] is not in configuredAccessories, adding it.
[12/13/2024, 5:03:25 PM] [KasaPython] KasaPython Platform finished launching
[12/13/2024, 5:03:25 PM] Homebridge v2.0.0-beta.23 (HAP v1.1.1-beta.7) (KasaPython) is running on port 43455.
[12/13/2024, 5:03:25 PM] [KasaPython] homebridge-kasa-python v2.7.0-beta.7, node v22.12.0, homebridge v2.0.0-beta.23, api v2.7 Initializing...
[12/13/2024, 5:03:25 PM] [KasaPython] Verifying environment
[12/13/2024, 5:03:25 PM] [KasaPython] Checking Node.js version
[12/13/2024, 5:03:26 PM] [KasaPython] Node.js version v22.12.0 satisfies the requirement ^18.20.5 || ^20.18.1 || ^22.12.0 || ^23.3.0
[12/13/2024, 5:03:26 PM] [KasaPython] Checking Homebridge version
[12/13/2024, 5:03:26 PM] [KasaPython] Homebridge version 2.0.0-beta.23 satisfies the requirement >= 1.8.4
[12/13/2024, 5:03:26 PM] [KasaPython] Checking for upgrade at path: /var/lib/homebridge/kasa-python/kasa-python-version.json
[12/13/2024, 5:03:26 PM] [KasaPython] Stored version: 2.7.0-beta.7
[12/13/2024, 5:03:26 PM] [KasaPython] No upgrade needed, version is up to date.
[12/13/2024, 5:03:26 PM] [KasaPython] Finished launching
[12/13/2024, 5:03:26 PM] [KasaPython] Checking Python environment
[12/13/2024, 5:03:26 PM] [KasaPython] Running PythonChecker with isUpgrade: false
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Starting python environment check...
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Ensuring plugin directory exists: /var/lib/homebridge/kasa-python
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Plugin directory already exists: /var/lib/homebridge/kasa-python
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Ensuring system Python version is supported
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Getting system Python version
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Running command: python3 --version
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Command PID: 959
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Command closed with exit code: 0
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Command finished.
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] System Python version: 3.12.3
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] System Python version is supported
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Ensuring virtual environment is created
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Virtual environment exists: true
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Virtual environment already exists
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Ensuring virtual environment uses correct Python home
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Getting Python home for executable: /var/lib/homebridge/kasa-python/.venv/bin/python3
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Running command: /var/lib/homebridge/kasa-python/.venv/bin/python3 /homebridge/node_modules/homebridge-kasa-python/dist/python/pythonHome.py
[12/13/2024, 5:03:26 PM] Homebridge v2.0.0-beta.23 (HAP v1.1.1-beta.7) (homebridge-alexa-smarthome) is running on port 38661.
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Command PID: 970
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Command closed with exit code: 0
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Command finished.
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Getting Python home for executable: python3
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Running command: python3 /homebridge/node_modules/homebridge-kasa-python/dist/python/pythonHome.py
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Command PID: 979
[12/13/2024, 5:03:26 PM] Homebridge v2.0.0-beta.23 (HAP v1.1.1-beta.7) (UniFi SmartPower) is running on port 35426.
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Command closed with exit code: 0
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Command finished.
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Virtual environment Python home: /usr/bin
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] System Python home: /usr/bin
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Python homes match
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Ensuring virtual environment pip is up to date
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Getting virtual environment pip version
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Running command: /var/lib/homebridge/kasa-python/.venv/bin/pip3 --version
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Command PID: 986
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Command closed with exit code: 1
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Command finished.
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Virtual environment pip version: undefined
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Fetching most recent pip version from PyPI
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Traceback (most recent call last):
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] File "/var/lib/homebridge/kasa-python/.venv/bin/pip3", line 5, in <module>
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] from pip._internal.cli.main import main
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] ModuleNotFoundError: No module named 'pip'
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Most recent pip version fetched: 24.3.1
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Updating pip in virtual environment
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Running command: /var/lib/homebridge/kasa-python/.venv/bin/pip3 install --upgrade pip
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Command PID: 1130
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Command closed with exit code: 1
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Command finished.
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Pip updated successfully
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Checking if virtual environment requirements are satisfied
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Running command: /var/lib/homebridge/kasa-python/.venv/bin/pip3 freeze
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Command PID: 1134
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Traceback (most recent call last):
  File "/var/lib/homebridge/kasa-python/.venv/bin/pip3", line 5, in <module>
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Traceback (most recent call last):
  File "/var/lib/homebridge/kasa-python/.venv/bin/pip3", line 5, in <module>
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Command closed with exit code: 1
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Command finished.
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Current virtual environment packages: {}
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Required packages: {
  "python-kasa": "0.8.1",
  "quart": "0.19.9",
  "uvicorn": "0.32.1"
}
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Requirements satisfied: false
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Installing requirements from: /homebridge/node_modules/homebridge-kasa-python/requirements.txt
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Running command: /var/lib/homebridge/kasa-python/.venv/bin/pip3 install -r /homebridge/node_modules/homebridge-kasa-python/requirements.txt
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Command PID: 1135
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Traceback (most recent call last):
  File "/var/lib/homebridge/kasa-python/.venv/bin/pip3", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Command closed with exit code: 1
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Command finished.
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Requirements installed successfully
[12/13/2024, 5:03:26 PM] [KasaPython] [Python Check] Python environment check completed successfully
[12/13/2024, 5:03:26 PM] [KasaPython] Getting available port
[12/13/2024, 5:03:26 PM] [KasaPython] Port assigned: 36687
[12/13/2024, 5:03:26 PM] [KasaPython] Initializing DeviceManager
[12/13/2024, 5:03:26 PM] [KasaPython] DeviceManager initialized
[12/13/2024, 5:03:26 PM] [KasaPython] Starting Kasa API with script: /homebridge/node_modules/homebridge-kasa-python/dist/python/kasaApi.py
[12/13/2024, 5:03:26 PM] [KasaPython] Running command: /var/lib/homebridge/kasa-python/.venv/bin/python3 /homebridge/node_modules/homebridge-kasa-python/dist/python/kasaApi.py 36687
[12/13/2024, 5:03:26 PM] [KasaPython] Command PID: 1136
[12/13/2024, 5:03:26 PM] [KasaPython] Command started and returning process.
[12/13/2024, 5:03:27 PM] [KasaPython] Process data received.
[12/13/2024, 5:03:27 PM] [KasaPython] Kasa API process started successfully
[12/13/2024, 5:03:27 PM] [KasaPython] Waiting for server at http://127.0.0.1:36687/health with timeout 30000ms and interval 1000ms
[12/13/2024, 5:03:27 PM] [KasaPython] Server not responding yet, retrying...
[12/13/2024, 5:03:28 PM] [KasaPython] Server not responding yet, retrying...
[12/13/2024, 5:03:29 PM] [KasaPython] Server not responding yet, retrying...
[12/13/2024, 5:03:30 PM] [KasaPython] Server not responding yet, retrying...
[12/13/2024, 5:03:31 PM] [KasaPython] Server not responding yet, retrying...
[12/13/2024, 5:03:32 PM] [KasaPython] Server not responding yet, retrying...
[12/13/2024, 5:03:33 PM] [KasaPython] Server not responding yet, retrying...
[12/13/2024, 5:03:34 PM] [KasaPython] Server not responding yet, retrying...
[12/13/2024, 5:03:35 PM] [KasaPython] Server not responding yet, retrying...
[12/13/2024, 5:03:36 PM] [KasaPython] Server not responding yet, retrying...
[12/13/2024, 5:03:37 PM] [KasaPython] Server not responding yet, retrying...
[12/13/2024, 5:03:38 PM] [KasaPython] Server not responding yet, retrying...
[12/13/2024, 5:03:39 PM] [KasaPython] Server not responding yet, retrying...
[12/13/2024, 5:03:40 PM] [KasaPython] Server not responding yet, retrying...
[12/13/2024, 5:03:41 PM] [KasaPython] Server not responding yet, retrying...
[12/13/2024, 5:03:42 PM] [KasaPython] Server not responding yet, retrying...
[12/13/2024, 5:03:43 PM] [KasaPython] Server not responding yet, retrying...
[12/13/2024, 5:03:44 PM] [KasaPython] Server not responding yet, retrying...
[12/13/2024, 5:03:45 PM] [KasaPython] Server not responding yet, retrying...
[12/13/2024, 5:03:46 PM] [KasaPython] Server not responding yet, retrying...
[12/13/2024, 5:03:47 PM] [KasaPython] Server not responding yet, retrying...
[12/13/2024, 5:03:48 PM] [KasaPython] Server not responding yet, retrying...
[12/13/2024, 5:03:49 PM] [KasaPython] Server not responding yet, retrying...
[12/13/2024, 5:03:50 PM] [KasaPython] Server not responding yet, retrying...
[12/13/2024, 5:03:51 PM] [KasaPython] Server not responding yet, retrying...
[12/13/2024, 5:03:52 PM] [KasaPython] Server not responding yet, retrying...
[12/13/2024, 5:03:53 PM] [KasaPython] Server not responding yet, retrying...
[12/13/2024, 5:03:54 PM] [KasaPython] Server not responding yet, retrying...
[12/13/2024, 5:03:55 PM] [KasaPython] Server not responding yet, retrying...
[12/13/2024, 5:03:56 PM] [KasaPython] Server not responding yet, retrying...
[12/13/2024, 5:03:57 PM] [KasaPython] Server did not respond within 30 seconds
[12/13/2024, 5:03:57 PM] [KasaPython] An error occurred during startup: Error: Server did not respond within 30 seconds
    at waitForServer (file:///homebridge/node_modules/homebridge-kasa-python/src/platform.ts:109:9)
    at KasaPythonPlatform.didFinishLaunching (file:///homebridge/node_modules/homebridge-kasa-python/src/platform.ts:222:7)
    at HomebridgeAPI.<anonymous> (file:///homebridge/node_modules/homebridge-kasa-python/src/platform.ts:142:7)
```

**Comment by ZeliardM** [comment]
@jakepez it seems that it's unable to find pip3 under the virtual python environment. Can you open the web UI terminal and do the following:
cd kasa-python
source .venv/bin/activate
pip3 --version

**Comment by jakepez** [comment]
@ZeliardM while the pip3 binary is there - the modules aren't properly installed  -

```
(.venv) root@Qnap:/var/lib/homebridge/kasa-python $ pip3 --version
Traceback (most recent call last):
  File "/var/lib/homebridge/kasa-python/.venv/bin/pip3", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'
(.venv) root@Qnap:/var/lib/homebridge/kasa-python $
```

Inside the virtual environment I then ran this (h/t [https://stackoverflow.com/questions/21826859/setting-up-a-virtualenv-no-module-named-pip)] ) which successfully (re)installs pip and then the plugin starts successfully.
`python -m ensurepip --default-pip`

This page also mentions using this when setting up the virtual env:
`virtualenv ENV --system-site-packages`

After running the ensurepip command above - here's the current state of pip:
```
root@Qnap:/var/lib/homebridge $ cd kasa-python/
root@Qnap:/var/lib/homebridge/kasa-python $ source .venv/bin/activate
(.venv) root@Qnap:/var/lib/homebridge/kasa-python $ pip3 --version
pip 24.3.1 from /var/lib/homebridge/kasa-python/.venv/lib/python3.12/site-packages/pip (python 3.12)
(.venv) root@Qnap:/var/lib/homebridge/kasa-python $ 
```

```
[12/13/2024, 8:28:21 PM] [KasaPython] Child bridge starting (pid 650)...
[12/13/2024, 8:28:21 PM] Registering platform 'homebridge-kasa-python.KasaPython'
[12/13/2024, 8:28:21 PM] [KasaPython] Child bridge started successfully (plugin v2.7.0-beta.7).
[12/13/2024, 8:28:21 PM] Loaded 3 cached accessories from cachedAccessories.0ED879189234.
[12/13/2024, 8:28:21 PM] Homebridge v2.0.0-beta.23 (HAP v1.1.1-beta.7) (KasaPython) is running on port 37861.
[12/13/2024, 8:28:21 PM] [KasaPython] homebridge-kasa-python v2.7.0-beta.7, node v22.12.0, homebridge v2.0.0-beta.23, api v2.7 Initializing...
[12/13/2024, 8:28:48 PM] [KasaPython] Discovering devices...
[12/13/2024, 8:28:56 PM] [KasaPython] Adding HomeKit device: [Power Strip 357E] IOT.SMARTPLUGSWITCH [8006DE8296BC3D937087AAD2777CCF341ECB972B] at host [10.XX.XX.XX]
[12/13/2024, 8:28:56 PM] [KasaPython] Adding HomeKit device: [Power Strip 7BC8] IOT.SMARTPLUGSWITCH [80060DD6969145188C731B20545E9D592104A138] at host [10.XX.XX.XX]
[12/13/2024, 8:28:56 PM] [KasaPython] Adding HomeKit device: [Power Strip F777] IOT.SMARTPLUGSWITCH [800628A133967FFD76328A8803E53BF122221AE5] at host [10.XX.XX.XX]
```

Is this something to be solved in the plugin or should I report this back up to the Docker Container maintainers?

**Comment by ZeliardM** [comment]
@jakepez try v2.7.0-beta.8 and let me know if that runs on fresh install. I force it to update pip when it creates the environment now.

**Comment by jakepez** [comment]
@ZeliardM - beta.8 works great. As an after thought, I went back and tested beta.7 on a complete fresh install as well - it actually didn't have any problems. I think my plugin python virtual environment may have been corrupted somehow from running previous versions and upgrading or something.

Thanks for the help. I think forcing the dependancies is smart with the upcoming upgrade to the Docker Container.

**Comment by ZeliardM** [comment]
@jakepez With the updated docker image today, can you give this a test on there?

**Comment by jakepez** [comment]
@ZeliardM - All looks good - tested with a complete fresh install with the new Docker image today with both  v1.8.5 and v2.0.0-beta.23.

Also running all good on my normal install with the updated Docker image.

**Comment by ZeliardM** [comment]
@jakepez can you check beta.12 and make sure that everything still works for you correctly?

**Comment by jakepez** [comment]
@ZeliardM all good on my install - 
Homebridge Installed: v2.0.0-beta.23
Docker - latest image

**Comment by ZeliardM** [comment]
Excellent, thanks!
