### ISSUE TITLE
Smart Dimmer Kasa HS220 HW 3.26 does not work 

### ISSUE THREAD

**Issue by itomaldonado** [ZeliardM/homebridge-kasa-python#6]
**Describe The Bug:**
Two bugs, somewhat related. They do not allow me to control the Smart Dimmer Kasa HS220 (US) HW 3.26

### Issue 1.

When using credentials, _all devices_ are discovered but they are not usable. These are the errors that I see.

*Note:*
* The `[Light Switch]` device is the HS220 in question.
* The `[Lamp]` device is a KP125(US) that works fine as a control.

```
[26/11/2024, 20:10:27] [TP Link Kasa - Python] 2024-11-26 20:10:27.712 | DEBUG    | __main__:get_sys_info_route:241 - Getting system info for device: xxx.xxx.xxx.164
[26/11/2024, 20:10:27] [TP Link Kasa - Python] 2024-11-26 20:10:27.716 | DEBUG    | __main__:get_device_info:176 - Getting device info for device: xxx.xxx.xxx.164
[26/11/2024, 20:10:27] [TP Link Kasa - Python] 2024-11-26 20:10:27.719 | ERROR    | flask.app:log_exception:875 - Exception on /getSysInfo [POST]
[26/11/2024, 20:10:27] [TP Link Kasa - Python] An error occurred during getSysInfo: Request failed with status code 500
[26/11/2024, 20:10:27] [TP Link Kasa - Python] Response status: 500
[26/11/2024, 20:10:27] [TP Link Kasa - Python] Response data: "<!doctype html>\n<html lang=en>\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n"
[26/11/2024, 20:10:27] [TP Link Kasa - Python] [Light Switch] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDeviceSwitch.updateState (file:///var/lib/homebridge/node_modules/homebridge-kasa-python/src/devices/homekitSwitch.ts:116:71)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[26/11/2024, 20:10:27] [TP Link Kasa - Python] 2024-11-26 20:10:27.724 | DEBUG    | __main__:get_sys_info_route:241 - Getting system info for device: xxx.xxx.xxx.193
[26/11/2024, 20:10:27] [TP Link Kasa - Python] 2024-11-26 20:10:27.739 | DEBUG    | __main__:get_device_info:176 - Getting device info for device: xxx.xxx.xxx.193
[26/11/2024, 20:10:27] [TP Link Kasa - Python] 2024-11-26 20:10:27.816 | DEBUG    | __main__:custom_device_serializer:37 - Serializing device: xxx.xxx.xxx.193
[26/11/2024, 20:10:27] [TP Link Kasa - Python] 2024-11-26 20:10:27.819 | ERROR    | __main__:get_device_info:189 - Error getting device info: 'dict' object has no attribute 'username'
[26/11/2024, 20:10:27] [TP Link Kasa - Python] An error occurred during getSysInfo: An unknown error occurred
[26/11/2024, 20:10:27] [TP Link Kasa - Python] [Lamp] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDevicePlug.updateState (file:///var/lib/homebridge/node_modules/homebridge-kasa-python/src/devices/homekitPlug.ts:119:71)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)

```

I can fix this issue currently with a workaround. By adding the following two lines right below [here ](https://github.com/ZeliardM/homebridge-kasa-python/blob/1e7eba9737ca032b37d2408869fde7ab12d04fac/src/python/kasaApi.py#L236)and [here](https://github.com/ZeliardM/homebridge-kasa-python/blob/1e7eba9737ca032b37d2408869fde7ab12d04fac/src/python/kasaApi.py#L244C10-L244C11):
```python
    credentials = device_config.get('credentials')
    device_config.update({'credentials': Credentials(username=credentials['username'], password=credentials['password'])} if credentials else {})
```

### Issue 2.

The Kasa Smart Switch / Dimmer HS220 HW 3.26 is discoverable but cannot be interacted with.

```
[26/11/2024, 20:19:49] [TP Link Kasa - Python] 2024-11-26 20:19:49.394 | DEBUG    | __main__:get_sys_info_route:241 - Getting system info for device: xxx.xxx.xxx.xxx.164
[26/11/2024, 20:19:49] [TP Link Kasa - Python] 2024-11-26 20:19:49.397 | DEBUG    | __main__:get_device_info:176 - Getting device info for device: xxx.xxx.xxx.xxx.164
[26/11/2024, 20:19:49] [TP Link Kasa - Python] 2024-11-26 20:19:49.542 | DEBUG    | __main__:custom_device_serializer:37 - Serializing device: xxx.xxx.xxx.xxx.164
[26/11/2024, 20:19:49] [TP Link Kasa - Python] 2024-11-26 20:19:49.546 | ERROR    | __main__:get_device_info:189 - Error getting device info: 'NoneType' object has no attribute 'get'
[26/11/2024, 20:19:49] [TP Link Kasa - Python] An error occurred during getSysInfo: An unknown error occurred
[26/11/2024, 20:19:49] [TP Link Kasa - Python] [Light Switch] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDeviceSwitch.updateState (file:///var/lib/homebridge/node_modules/homebridge-kasa-python/src/devices/homekitSwitch.ts:116:71)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
```

Seems like this is related to the way the `model` is retrieved [here](https://github.com/ZeliardM/homebridge-kasa-python/blob/1e7eba9737ca032b37d2408869fde7ab12d04fac/src/python/kasaApi.py#L49).

The `device._discovery_info` dictionary is **ONLY** populated during discovery, but during any other operation it is not, so calls to `/getSysInfo` will fail.

You *could* default to just get `device.model` but I saw what the code is trying to do (get the model with the region in parenthesis) but the HS220 HW3.26 does not have the region in the `device.model` but it does have it in `device._discovery_info.get("device_model")` during discovery 🤷‍♂️ ....

I '_patched_' my simply doing what you see below, but I do think we may need a better solution...
```python
"model": device.model if "(" in device.model else f'{device.model}(US)',
```

**To Reproduce:**
Have a HS220 HW3.26 available.... and plugin version 2.62

**Expected behavior:**
The HS220 HW3.26 should be discoverable and work as a switch.

**Logs:** see above~

**Plugin Config:**

```json
{
    "name": "TP Link Kasa - Python",
    "enableCredentials": true,
    "username": "xxx@example.com",
    "password": "some-super-secret-password",
    "manualDevices": [
        {
            "alias": "Will Be Filled By Plug-In Automatically"
        }
    ],
    "platform": "KasaPython",
    "_bridge": {
        "username": "SOME-MAC-HERE",
        "port": 12345
    }
}
```

**Screenshots:** N/A

**Environment:** RaspberyPi 5
* **Plugin Version**: 2.62
* **Homebridge Version**: 1.8.5
* **Node.js Version**:  v22.11.0
* **NPM Version**: 10.9.0
* **Operating System**: Raspbian /  Debian GNU/Linux Bookworm (12)

**Comment by ZeliardM** [comment]
@itomaldonado I'll work on the credential piece for issue 1.

The problem with issue 2 was the region like you stated. I'm going to figure out a different way to pull in the model with the correct country code as just adding US won't work for all devices.

I'll keep poking at it later tonight and let you know. Thanks for the details!

**Comment by itomaldonado** [comment]
@ZeliardM any way that I can help, let me know. I am just not intimately familiar with the underlying TPLink/Kasa Library, but I can troubleshoot stuff if you need me to!

**Comment by ZeliardM** [comment]
Try v2.6.3 and let me know.

**Comment by ZeliardM** [comment]
@itomaldonado I noticed in your config there's a manual device with that default alias, but no host, did you remove host or did it put alias there? May need to clean up that portion of the code if it did it on it's own.

**Comment by itomaldonado** [comment]
Hey @ZeliardM, I just copied the configuration from HomeBridge. They come from a fresh install where they only thing I added was the username/password + change the name of the plugin. Not sure why that entry is there.

**Comment by ZeliardM** [comment]
@itomaldonado ok, sounds good. I will keep poking at that and see if I can figure that out. Let me know if v2.6.3 works for controlling and updating the devices now.

**Comment by MichaelCWarren** [comment]
I'm getting a similar issue with v2.6.3

This is with a combination of HS200 (hw 5.26 fw 1.0.3), KS200 (hw 1.0  fw 1.05), HS210 (hw 3.0 fw 1.0.10), HS103 (hw 3.0 fw 1.0.4), P115 (hw 1.0 fw 1.1.3).

Many edits: added versions

```
[11/27/2024, 9:39:43 AM] [KasaPython] An error occurred during getSysInfo: connect ECONNREFUSED 127.0.0.1:40165
[11/27/2024, 9:39:43 AM] [KasaPython] [Basement Storage Room] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDeviceSwitch.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitSwitch.ts:116:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 9:39:43 AM] [KasaPython] An error occurred during getSysInfo: connect ECONNREFUSED 127.0.0.1:40165
[11/27/2024, 9:39:43 AM] [KasaPython] [Basement Closet] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDeviceSwitch.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitSwitch.ts:116:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 9:39:43 AM] [KasaPython] An error occurred during getSysInfo: connect ECONNREFUSED 127.0.0.1:40165
[11/27/2024, 9:39:43 AM] [KasaPython] [Utility Room] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDeviceSwitch.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitSwitch.ts:116:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 9:39:43 AM] [KasaPython] An error occurred during getSysInfo: connect ECONNREFUSED 127.0.0.1:40165
[11/27/2024, 9:39:43 AM] [KasaPython] [Plug #1] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDevicePlug.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitPlug.ts:119:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 9:39:43 AM] [KasaPython] An error occurred during getSysInfo: connect ECONNREFUSED 127.0.0.1:40165
[11/27/2024, 9:39:43 AM] [KasaPython] [Basement Hallway Light] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDeviceSwitch.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitSwitch.ts:116:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 9:39:43 AM] [KasaPython] An error occurred during getSysInfo: connect ECONNREFUSED 127.0.0.1:40165
[11/27/2024, 9:39:43 AM] [KasaPython] [Basement Lights] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDevicePlug.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitPlug.ts:119:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 9:39:43 AM] [KasaPython] An error occurred during getSysInfo: connect ECONNREFUSED 127.0.0.1:40165
[11/27/2024, 9:39:43 AM] [KasaPython] [Plug #3] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDevicePlug.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitPlug.ts:119:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 9:39:43 AM] [KasaPython] An error occurred during getSysInfo: connect ECONNREFUSED 127.0.0.1:40165
[11/27/2024, 9:39:43 AM] [KasaPython] [Plug #4] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDevicePlug.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitPlug.ts:119:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 9:39:43 AM] [KasaPython] An error occurred during getSysInfo: connect ECONNREFUSED 127.0.0.1:40165
[11/27/2024, 9:39:43 AM] [KasaPython] [Plug #5] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDevicePlug.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitPlug.ts:119:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 9:39:43 AM] [KasaPython] An error occurred during getSysInfo: connect ECONNREFUSED 127.0.0.1:40165
[11/27/2024, 9:39:43 AM] [KasaPython] [Plug #6] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDevicePlug.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitPlug.ts:119:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by ZeliardM** [comment]
@MichaelCWarren ECONNREFUSED sounds like it's having a problem connecting to the device. Would you be able to give more detail of the setup? Can you open a new issue and provide full logs from a restart of the plugin and the config? Please scrub any personal information.

**Comment by itomaldonado** [comment]
@ZeliardM do you have discord? I think we can debug this further. 

I still have issues with the device model.

EDIT:

But for clarity, the issue is that [this line](https://github.com/ZeliardM/homebridge-kasa-python/blob/9f82c057690f1744a0a45cebf3fdf98577d148e2/src/python/kasaApi.py#L49) still breaks:
```python
        "model": device.model if "(" in device.model else (device._discovery_info.get("device_model") or device.model),
```

I'd recommend something like this:
```python
        "model": device.model if ("(" in device.model or not device._discovery_info) else device._discovery_info.get("device_model"),

```

Mostly because the private field `device._discovery_info` doesn't always get created so it may be `None`

**Comment by ZeliardM** [comment]
Yea, same handle, just shoot me a PM.

**Comment by MichaelCWarren** [comment]
> @MichaelCWarren ECONNREFUSED sounds like it's having a problem connecting to the device. Would you be able to give more detail of the setup? Can you open a new issue and provide full logs from a restart of the plugin and the config? Please scrub any personal information.

Looks like maybe that's after the child bridge is stopped.

```
[11/27/2024, 10:38:27 AM] [KasaPython] An error occurred during getSysInfo: An unknown error occurred
[11/27/2024, 10:38:27 AM] [KasaPython] [Plug #6] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDevicePlug.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitPlug.ts:119:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I created another support ticket.  Thanks for your help!

**Comment by ZeliardM** [comment]
SMART Device functionality for Plug, Switch, and Power Strips working, user and I will continue to work on Dimmer functionality through a fork and PR later.

**Comment by ZeliardM** [comment]
I've got v2.7.0-beta.1 out now with initial support for dimmers and lights
