### ISSUE TITLE
Devices are found, but unable to get state

### ISSUE THREAD

**Issue by MichaelCWarren** [ZeliardM/homebridge-kasa-python#7]
**Describe Your Problem:**

None of the added accessories are able to connect and be used. 

**Logs:**

```
[11/27/2024, 10:37:53 AM] The plugin "homebridge-kasa-python" requires Node.js version of ^18.20.5 || ^20.18.1 || ^22.11.0 || ^23.3.0 which does not satisfy the current Node.js version of v20.18.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF
[11/27/2024, 10:37:53 AM] Registering platform 'homebridge-kasa-python.KasaPython'
[11/27/2024, 10:37:53 AM] [KasaPython] Loaded homebridge-kasa-python v2.6.3 child bridge successfully
[11/27/2024, 10:37:53 AM] Loaded 10 cached accessories from cachedAccessories.0E2A04E78A81.
[11/27/2024, 10:37:54 AM] [KasaPython] Configuring cached accessory: [Plug #1] UUID: 4a2f341c-0015-4dc9-b288-83b9702061ce deviceId: 8006699A8EF664C511918B48F20964481D88BC42
[11/27/2024, 10:37:54 AM] [KasaPython] Configuring cached accessory: [Basement Hallway Light] UUID: 269f599c-9352-4ee5-a750-7e98b4035abd deviceId: 800666B229190D9E23E52759F6CE51BC229A201F
[11/27/2024, 10:37:54 AM] [KasaPython] Configuring cached accessory: [Basement Lights] UUID: eab5c890-5887-40cc-8d67-1af046eb1aff deviceId: 8006963671511E280A75368D9E8A48DE2211110B
[11/27/2024, 10:37:54 AM] [KasaPython] Configuring cached accessory: [Basement Storage Room] UUID: fd690d5e-c4fb-4563-9148-f60be4cc8ee2 deviceId: 803B99396117E72161BB840F677AC5BE22963A21
[11/27/2024, 10:37:54 AM] [KasaPython] Configuring cached accessory: [Basement Closet] UUID: b031c0a8-e89e-434d-89e9-411049009dc9 deviceId: 803B7FAE6002E41DBEC1B080A111BDAE2296441E
[11/27/2024, 10:37:54 AM] [KasaPython] Configuring cached accessory: [Utility Room] UUID: 1d337c77-ad65-4b42-b8d8-e4b83a656ed6 deviceId: 803B2FCB7EC0D83E5CF556962B5BA399229634EA
[11/27/2024, 10:37:54 AM] [KasaPython] Configuring cached accessory: [Plug #3] UUID: f8e29480-9ef0-41e2-8ad7-d69f14105145 deviceId: 8022CBFEEB4730D98CC38A3AE9A2CC9D2331247C
[11/27/2024, 10:37:54 AM] [KasaPython] Configuring cached accessory: [Plug #4] UUID: ac428232-c724-46ae-8291-978c608e0c65 deviceId: 80221648450C447544AD147427EE20D423310C17
[11/27/2024, 10:37:54 AM] [KasaPython] Configuring cached accessory: [Plug #5] UUID: 30baa194-a854-49f8-a9d3-394443437ec8 deviceId: 802203F0BE4F0819F4B63D76F35DE7C623304406
[11/27/2024, 10:37:54 AM] [KasaPython] Configuring cached accessory: [Plug #6] UUID: 0614340c-f4d3-4cf1-972a-5d8fbdff1646 deviceId: 80220063F8FC08B605533DD7BBE7F6FA233147E5
[11/27/2024, 10:37:54 AM] Homebridge v1.8.5 (HAP v0.12.3) (KasaPython) is running on port 56395.
[11/27/2024, 10:37:54 AM] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[11/27/2024, 10:37:54 AM] [KasaPython] homebridge-kasa-python v2.6.3, node v20.18.0, homebridge v1.8.5, api v2.7 Initializing...
[11/27/2024, 10:37:54 AM] [KasaPython] Error: not using minimum node version ^18.20.5 || ^20.18.1 || ^22.11.0 || ^23.3.0
[11/27/2024, 10:38:00 AM] [KasaPython] Discovering devices...
[11/27/2024, 10:38:11 AM] [KasaPython] Devices discovered: 10
[11/27/2024, 10:38:11 AM] [KasaPython] Adding: [Utility Room] SMART.KASASWITCH [803B2FCB7EC0D83E5CF556962B5BA399229634EA]
[11/27/2024, 10:38:11 AM] [KasaPython] Adding: [Plug #1] IOT.SMARTPLUGSWITCH [8006699A8EF664C511918B48F20964481D88BC42]
[11/27/2024, 10:38:11 AM] [KasaPython] Adding: [Basement Hallway Light] IOT.SMARTPLUGSWITCH [800666B229190D9E23E52759F6CE51BC229A201F]
[11/27/2024, 10:38:11 AM] [KasaPython] Adding: [Basement Lights] IOT.SMARTPLUGSWITCH [8006963671511E280A75368D9E8A48DE2211110B]
[11/27/2024, 10:38:11 AM] [KasaPython] Adding: [Plug #3] SMART.TAPOPLUG [8022CBFEEB4730D98CC38A3AE9A2CC9D2331247C]
[11/27/2024, 10:38:11 AM] [KasaPython] Adding: [Plug #4] SMART.TAPOPLUG [80221648450C447544AD147427EE20D423310C17]
[11/27/2024, 10:38:11 AM] [KasaPython] Adding: [Plug #5] SMART.TAPOPLUG [802203F0BE4F0819F4B63D76F35DE7C623304406]
[11/27/2024, 10:38:11 AM] [KasaPython] Adding: [Plug #6] SMART.TAPOPLUG [80220063F8FC08B605533DD7BBE7F6FA233147E5]
[11/27/2024, 10:38:11 AM] [KasaPython] Adding: [Basement Storage Room] SMART.KASASWITCH [803B99396117E72161BB840F677AC5BE22963A21]
[11/27/2024, 10:38:11 AM] [KasaPython] Adding: [Basement Closet] SMART.KASASWITCH [803B7FAE6002E41DBEC1B080A111BDAE2296441E]
[11/27/2024, 10:38:16 AM] [KasaPython] An error occurred during getSysInfo: An unknown error occurred
[11/27/2024, 10:38:16 AM] [KasaPython] [Utility Room] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDeviceSwitch.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitSwitch.ts:116:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:17 AM] [KasaPython] An error occurred during getSysInfo: An unknown error occurred
[11/27/2024, 10:38:17 AM] [KasaPython] [Plug #3] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDevicePlug.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitPlug.ts:119:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:17 AM] [KasaPython] An error occurred during getSysInfo: An unknown error occurred
[11/27/2024, 10:38:17 AM] [KasaPython] [Plug #4] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDevicePlug.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitPlug.ts:119:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:17 AM] [KasaPython] An error occurred during getSysInfo: An unknown error occurred
[11/27/2024, 10:38:17 AM] [KasaPython] [Plug #5] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDevicePlug.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitPlug.ts:119:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:17 AM] [KasaPython] An error occurred during getSysInfo: An unknown error occurred
[11/27/2024, 10:38:17 AM] [KasaPython] [Plug #6] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDevicePlug.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitPlug.ts:119:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:17 AM] [KasaPython] An error occurred during getSysInfo: An unknown error occurred
[11/27/2024, 10:38:17 AM] [KasaPython] [Basement Storage Room] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDeviceSwitch.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitSwitch.ts:116:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:18 AM] [KasaPython] An error occurred during getSysInfo: An unknown error occurred
[11/27/2024, 10:38:18 AM] [KasaPython] [Basement Closet] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDeviceSwitch.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitSwitch.ts:116:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:21 AM] [KasaPython] An error occurred during getSysInfo: An unknown error occurred
[11/27/2024, 10:38:21 AM] [KasaPython] [Utility Room] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDeviceSwitch.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitSwitch.ts:116:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:21 AM] [KasaPython] An error occurred during getSysInfo: An unknown error occurred
[11/27/2024, 10:38:21 AM] [KasaPython] [Plug #3] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDevicePlug.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitPlug.ts:119:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:22 AM] [KasaPython] An error occurred during getSysInfo: An unknown error occurred
[11/27/2024, 10:38:22 AM] [KasaPython] [Plug #6] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDevicePlug.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitPlug.ts:119:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:22 AM] [KasaPython] An error occurred during getSysInfo: An unknown error occurred
[11/27/2024, 10:38:22 AM] [KasaPython] [Plug #4] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDevicePlug.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitPlug.ts:119:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:22 AM] [KasaPython] An error occurred during getSysInfo: An unknown error occurred
[11/27/2024, 10:38:22 AM] [KasaPython] [Basement Storage Room] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDeviceSwitch.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitSwitch.ts:116:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:22 AM] [KasaPython] An error occurred during getSysInfo: An unknown error occurred
[11/27/2024, 10:38:22 AM] [KasaPython] [Plug #5] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDevicePlug.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitPlug.ts:119:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:22 AM] [KasaPython] An error occurred during getSysInfo: An unknown error occurred
[11/27/2024, 10:38:22 AM] [KasaPython] [Basement Closet] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDeviceSwitch.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitSwitch.ts:116:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:26 AM] [KasaPython] An error occurred during getSysInfo: An unknown error occurred
[11/27/2024, 10:38:26 AM] [KasaPython] [Utility Room] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDeviceSwitch.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitSwitch.ts:116:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:26 AM] [KasaPython] An error occurred during getSysInfo: An unknown error occurred
[11/27/2024, 10:38:26 AM] [KasaPython] [Basement Storage Room] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDeviceSwitch.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitSwitch.ts:116:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:27 AM] [KasaPython] An error occurred during getSysInfo: An unknown error occurred
[11/27/2024, 10:38:27 AM] [KasaPython] [Plug #5] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDevicePlug.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitPlug.ts:119:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:27 AM] [KasaPython] An error occurred during getSysInfo: An unknown error occurred
[11/27/2024, 10:38:27 AM] [KasaPython] [Plug #6] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDevicePlug.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitPlug.ts:119:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:27 AM] [KasaPython] An error occurred during getSysInfo: An unknown error occurred
[11/27/2024, 10:38:27 AM] [KasaPython] [Basement Closet] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDeviceSwitch.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitSwitch.ts:116:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:27 AM] [KasaPython] An error occurred during getSysInfo: An unknown error occurred
[11/27/2024, 10:38:27 AM] [KasaPython] [Plug #4] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDevicePlug.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitPlug.ts:119:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:27 AM] [KasaPython] An error occurred during getSysInfo: An unknown error occurred
[11/27/2024, 10:38:27 AM] [KasaPython] [Plug #3] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDevicePlug.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitPlug.ts:119:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:31 AM] [KasaPython] An error occurred during getSysInfo: An unknown error occurred
[11/27/2024, 10:38:31 AM] [KasaPython] [Utility Room] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDeviceSwitch.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitSwitch.ts:116:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:31 AM] [KasaPython] An error occurred during getSysInfo: An unknown error occurred
[11/27/2024, 10:38:31 AM] [KasaPython] [Plug #5] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDevicePlug.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitPlug.ts:119:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:31 AM] [KasaPython] An error occurred during getSysInfo: An unknown error occurred
[11/27/2024, 10:38:31 AM] [KasaPython] [Basement Storage Room] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDeviceSwitch.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitSwitch.ts:116:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:32 AM] [KasaPython] An error occurred during getSysInfo: An unknown error occurred
[11/27/2024, 10:38:32 AM] [KasaPython] [Basement Closet] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDeviceSwitch.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitSwitch.ts:116:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:32 AM] [KasaPython] An error occurred during getSysInfo: An unknown error occurred
[11/27/2024, 10:38:32 AM] [KasaPython] [Plug #6] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDevicePlug.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitPlug.ts:119:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:32 AM] [KasaPython] An error occurred during getSysInfo: An unknown error occurred
[11/27/2024, 10:38:32 AM] [KasaPython] [Plug #3] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDevicePlug.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitPlug.ts:119:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:32 AM] [KasaPython] An error occurred during getSysInfo: An unknown error occurred
[11/27/2024, 10:38:32 AM] [KasaPython] [Plug #4] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDevicePlug.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitPlug.ts:119:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:35 AM] [KasaPython] Stopping child bridge (will not restart)...
[11/27/2024, 10:38:35 AM] Got SIGTERM, shutting down child bridge process...
[11/27/2024, 10:38:36 AM] [KasaPython] An error occurred during getSysInfo: connect ECONNREFUSED 127.0.0.1:42743
[11/27/2024, 10:38:36 AM] [KasaPython] [Utility Room] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDeviceSwitch.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitSwitch.ts:116:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:36 AM] [KasaPython] An error occurred during getSysInfo: connect ECONNREFUSED 127.0.0.1:42743
[11/27/2024, 10:38:36 AM] [KasaPython] [Plug #1] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDevicePlug.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitPlug.ts:119:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:36 AM] [KasaPython] An error occurred during getSysInfo: connect ECONNREFUSED 127.0.0.1:42743
[11/27/2024, 10:38:36 AM] [KasaPython] [Basement Hallway Light] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDeviceSwitch.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitSwitch.ts:116:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:36 AM] [KasaPython] An error occurred during getSysInfo: connect ECONNREFUSED 127.0.0.1:42743
[11/27/2024, 10:38:36 AM] [KasaPython] [Basement Lights] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDevicePlug.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitPlug.ts:119:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:36 AM] [KasaPython] An error occurred during getSysInfo: connect ECONNREFUSED 127.0.0.1:42743
[11/27/2024, 10:38:36 AM] [KasaPython] [Plug #3] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDevicePlug.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitPlug.ts:119:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:36 AM] [KasaPython] An error occurred during getSysInfo: connect ECONNREFUSED 127.0.0.1:42743
[11/27/2024, 10:38:36 AM] [KasaPython] [Plug #4] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDevicePlug.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitPlug.ts:119:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:36 AM] [KasaPython] An error occurred during getSysInfo: connect ECONNREFUSED 127.0.0.1:42743
[11/27/2024, 10:38:36 AM] [KasaPython] [Plug #5] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDevicePlug.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitPlug.ts:119:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:36 AM] [KasaPython] An error occurred during getSysInfo: connect ECONNREFUSED 127.0.0.1:42743
[11/27/2024, 10:38:36 AM] [KasaPython] [Plug #6] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDevicePlug.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitPlug.ts:119:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:36 AM] [KasaPython] An error occurred during getSysInfo: connect ECONNREFUSED 127.0.0.1:42743
[11/27/2024, 10:38:36 AM] [KasaPython] [Basement Storage Room] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDeviceSwitch.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitSwitch.ts:116:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:36 AM] [KasaPython] An error occurred during getSysInfo: connect ECONNREFUSED 127.0.0.1:42743
[11/27/2024, 10:38:36 AM] [KasaPython] [Basement Closet] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDeviceSwitch.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitSwitch.ts:116:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/27/2024, 10:38:40 AM] [KasaPython] Child bridge process ended
```

**Plugin Config:**

```json
{
    "name": "KasaPython",
    "enableCredentials": true,
    "username": "username",
    "password": "password",
    "manualDevices": [
        {
            "alias": "Will Be Filled By Plug-In Automatically"
        }
    ],
    "_bridge": {
        "username": "0E:2A:04:E7:8A:81",
        "port": 56395
    },
    "platform": "KasaPython"
}
```

**Environment:**

* **Plugin Version**: 2.6.3
* **Homebridge Version**: 1.8.5
* **Node.js Version**: v20.18.0
* **NPM Version**: ¯\_(ツ)_/¯ 
* **Operating System**:  Docker homebridge/homebridge:latest

**Comment by ZeliardM** [comment]
@MichaelCWarren yea, that is part of the same problem I am running into on the other issue. I am working on it and hopefully will have something soon. You are correct, the connection error is when the plug-in restarts due to it shutting down the api before the commands have stopped.

**Comment by MichaelCWarren** [comment]
> @MichaelCWarren yea, that is part of the same problem I am running into on the other issue. I am working on it and hopefully will have something soon. You are correct, the connection error is when the plug-in restarts due to it shutting down the api before the commands have stopped.

Okay, thanks.  Good to know you're on it!

Maybe this will help as well.

```
[11/27/2024, 10:52:46 AM] [KasaPython] 2024-11-27 10:52:46.470 | DEBUG    | __main__:get_sys_info_route:237 - Getting system info for device: 192.168.4.52
[11/27/2024, 10:52:46 AM] [KasaPython] 2024-11-27 10:52:46.472 | DEBUG    | __main__:get_device_info:174 - Getting device info for device: 192.168.4.52
[11/27/2024, 10:52:46 AM] [KasaPython] 2024-11-27 10:52:46.555 | DEBUG    | __main__:custom_device_serializer:35 - Serializing device: 192.168.4.52
[11/27/2024, 10:52:49 AM] [KasaPython] [Plug #1] executing deferred getSysInfo count: 1
[11/27/2024, 10:52:49 AM] [KasaPython] [Basement Hallway Light] executing deferred getSysInfo count: 1
[11/27/2024, 10:52:49 AM] [KasaPython] [Basement Lights] executing deferred getSysInfo count: 1
[11/27/2024, 10:52:49 AM] [KasaPython] 2024-11-27 10:52:49.877 | DEBUG    | __main__:get_sys_info_route:237 - Getting system info for device: 192.168.4.50
[11/27/2024, 10:52:49 AM] [KasaPython] 2024-11-27 10:52:49.880 | DEBUG    | __main__:get_device_info:174 - Getting device info for device: 192.168.4.50
[11/27/2024, 10:52:49 AM] [KasaPython] [Plug #3] executing deferred getSysInfo count: 1
[11/27/2024, 10:52:49 AM] [KasaPython] [Plug #4] executing deferred getSysInfo count: 1
[11/27/2024, 10:52:49 AM] [KasaPython] [Plug #5] executing deferred getSysInfo count: 1
[11/27/2024, 10:52:49 AM] [KasaPython] [Plug #6] executing deferred getSysInfo count: 1
[11/27/2024, 10:52:49 AM] [KasaPython] [Utility Room] executing deferred getSysInfo count: 1
[11/27/2024, 10:52:49 AM] [KasaPython] [Basement Storage Room] executing deferred getSysInfo count: 1
[11/27/2024, 10:52:49 AM] [KasaPython] [Basement Closet] executing deferred getSysInfo count: 1
[11/27/2024, 10:52:49 AM] [KasaPython] 2024-11-27 10:52:49.970 | DEBUG    | __main__:custom_device_serializer:35 - Serializing device: 192.168.4.50
[11/27/2024, 10:52:49 AM] [KasaPython] 2024-11-27 10:52:49.974 | DEBUG    | __main__:get_sys_info_route:237 - Getting system info for device: 192.168.4.61
[11/27/2024, 10:52:49 AM] [KasaPython] 2024-11-27 10:52:49.976 | DEBUG    | __main__:get_device_info:174 - Getting device info for device: 192.168.4.61
[11/27/2024, 10:52:50 AM] [KasaPython] 2024-11-27 10:52:50.114 | DEBUG    | __main__:custom_device_serializer:35 - Serializing device: 192.168.4.61
[11/27/2024, 10:52:50 AM] [KasaPython] 2024-11-27 10:52:50.117 | ERROR    | __main__:get_device_info:185 - Error getting device info: 'NoneType' object has no attribute 'get'
[11/27/2024, 10:52:50 AM] [KasaPython] An error occurred during getSysInfo: An unknown error occurred
[11/27/2024, 10:52:50 AM] [KasaPython] [Basement Closet] Error updating device state: TypeError: Cannot read properties of undefined (reading 'state')
    at HomeKitDeviceSwitch.updateState (file:///homebridge/node_modules/homebridge-kasa-python/src/devices/homekitSwitch.ts:116:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by ZeliardM** [comment]
Give v2.6.8 a shot and if you're good, close out the issue please.

**Comment by MichaelCWarren** [comment]
So far, so good!  Thanks!
